name: Release

on:
  push:
    branches:
      - main

jobs:

  tests:
    uses: ./.github/workflows/test.yml

  build:
    needs: [tests]
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [windows-latest]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.19.1
      - name: Build wheels
        run: python -m cibuildwheel --output-dir dist
        env:
          CIBW_ENVIRONMENT: HNSWLIB_NO_NATIVE=true
          CIBW_ENVIRONMENT_PASS_LINUX: HNSWLIB_NO_NATIVE
          CIBW_PROJECT_REQUIRES_PYTHON: ">=3.7"
          CIBW_SKIP: "pp* *musllinux* cp312-win*"
          CIBW_ARCHS_MACOS: "x86_64 arm64"
          CIBW_ARCHS_WINDOWS: "AMD64"
          CIBW_ARCHS_LINUX: "x86_64 aarch64"
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: python-package-distributions
          path: dist
